import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import ProjectDashboardLayout from "@/components/common/layout/projectLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: { id: string }
}>) {
  return (
  <ProjectDashboardLayout>
    {children}
    
  </ProjectDashboardLayout>
  )
}
